### ISSUE TITLE
Update frequency for datagrip

### ISSUE THREAD

**Issue by metalshanked** [projectorimages/jet-builder#1]
@BabisK 
First of all Thanks for making this available in Docker Hub!  It is really helpful!.
Forgive my ignorance but i see some of the products like Pycharm are updated recently but other products like "DataGrip" are from a couple of weeks back.

I thought that the "projector" components (like Projector Server, Client etc) are the same for all the products so wouldn't there be an update for DataGrip as well if Pycharm has been updated ?

Thanks again!

**Comment by BabisK** [comment]
Hello @metalshanked ,

I've made the decision to update the images when there's an update on the IDE, not on projector. So, pycharm has released minor version updates but DataGrip hasn't.

Projector is under active development and rebuilding all IDE versions for each commit in master is more confusing for users I think.

So, new Projector server version will be incorporated when there is a new IDE released.

Of course if there is a specific projector bug that is fixed on master and you need it, let me know and I will rebuild the latest tags.

**Comment by metalshanked** [comment]
Thanks, yes. there is a drastic improvement in the new DG image released recently due to the projector server improvements.

**Comment by metalshanked** [comment]
Hi @BabisK - Would it be possible for you to make a new image build for DataGrip?  Seems like the projector server has many redrawing improvements in yesterdays change-log.

Thanks!
